In [1]:
from Bio.SeqIO.FastaIO import SimpleFastaParser
from Bio.SeqUtils import gc_fraction

import config_readwrite as crw
import glob

import matplotlib.pyplot as plt
import numpy as np
import os, sys

import pandas as pd

from scipy import stats
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler


from plot_params import fonts

In [2]:
config, cfn = crw.read(os.path.join(os.path.dirname(os.getcwd()), "config.ini"))

# dependent variables
section = "data"

MPRA = config[section]["HEPG2.clean"]

# independent variables
section = "FIMO"

FIMO_MOTIF_MAX_TABLE = config[section]["max_score_table"]
FIMO_MOTIF_MAX_PTABLE = config[section]["max_score_pval_table"]

## load US

In [19]:
us = pd.read_csv(MPRA, sep='\t')
us.head()

,name,label,ratio.med.ctrl,label.ctrl,ratio.1.ctrl,ratio.2.ctrl,ratio.3.ctrl,ratio.med.us,label.us,ratio.1.us,...,pval,logFC,response,cl.origin,type,coor,ratio.mean.ctrl,ratio.std.ctrl,ratio.mean.us,ratio.std.us
0,SYNTHETIC:_Added_CCTTCCTG_GCCCGGGGG_TATACATA_a...,synthetic,0.488151,inactive,0.480700,0.488151,0.491067,0.569507,inactive,0.559691,...,0.000080,0.222385,unresponsive,NaN,synthetic,NaN,0.486639,0.005346,0.566745,0.006157
1,hob_k27ac_up_chr1:67427680-67427949,k27ac,0.758301,inactive,0.758301,0.763843,0.753815,0.686366,inactive,0.686366,...,0.000146,-0.143792,unresponsive,hob,k27ac,chr1:67427680-67427949,0.758653,0.005023,0.688406,0.006234
2,SYNTHETIC:_The_motif_ATTAAA_was_added_in_Pos:8...,synthetic,0.712807,inactive,0.729310,0.712807,0.711749,0.864872,inactive,0.864872,...,0.000177,0.278975,unresponsive,NaN,synthetic,NaN,0.717955,0.009848,0.864591,0.013279
3,SYNTHETIC:_Added_TATGACTCATA_ACAGGTGTAC_ACAGGT...,synthetic,0.860961,inactive,0.889910,0.848101,0.860961,0.624727,inactive,0.624727,...,0.000177,-0.462723,unresponsive,NaN,synthetic,NaN,0.866324,0.021414,0.636227,0.020327
4,k562_atac_up_chr15:78056378-78056647,atac,1.662392,active,1.640097,1.662392,1.674355,1.441707,active,1.450990,...,0.000201,-0.205483,ultrasound-responsive,k562,atac,chr15:78056378-78056647,1.658948,0.017387,1.434116,0.021689

## clean up US
- remove synthetic sequences
- group sequences that overlap to reduce data leakage

# load fimo
- issue - need names of sequences.

In [4]:
tf = pd.read_csv(FIMO_MOTIF_MAX_TABLE, sep='\t')

tf.head()

,MA0001.2,MA0002.2,MA0003.4,MA0005.2,MA0007.3,MA0009.2,MA0010.1,MA0011.1,MA0012.1,MA0013.1,...,MA1983.1,MA1984.1,MA1985.1,MA1986.1,MA2005.1,MA2006.1,MA2007.1,MA2008.1,MA2009.1,MA2010.1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12.8455,NaN,NaN,NaN,NaN,12.5102
1,NaN,NaN,NaN,NaN,13.4828,NaN,14.6757,NaN,NaN,12.1339,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,14.6757,NaN,NaN,11.4094,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.5669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
transform = MaxAbsScaler()
t = pd.DataFrame(transform.fit_transform(tf))
t

,0,1,2,3,4,5,6,7,8,9,...,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.963415,NaN,NaN,NaN,NaN,0.904132
1,NaN,NaN,NaN,NaN,0.601540,NaN,0.888225,NaN,NaN,0.803442,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,0.888225,NaN,NaN,0.755469,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.765898,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82424,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82425,NaN,NaN,0.567606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82426,NaN,NaN,0.567606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82427,NaN,NaN,NaN,NaN,0.382308,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.425957,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
pipe = Pipeline([('scaler', MaxAbsScaler()), ('reg', LinearRegression())])

X = np.vstack(us["logFC"])
y = np.vstack(us["logFC"])

pipe.fit(X, y)

print(pipe.score(X, y))

reg = pipe.named_steps["reg"]

ValueError: Found input variables with inconsistent numbers of samples: [1677, 67994]

In [18]:
list(us)

['name',
 'label',
 'ratio.med.ctrl',
 'label.ctrl',
 'ratio.1.ctrl',
 'ratio.2.ctrl',
 'ratio.3.ctrl',
 'ratio.med.us',
 'label.us',
 'ratio.1.us',
 'ratio.2.us',
 'ratio.3.us',
 'pval',
 'logFC',
 'response',
 'cl.origin',
 'type',
 'coor',
 'ratio.mean.ctrl',
 'ratio.std.ctrl',
 'ratio.mean.us',
 'ratio.std.us']

In [15]:
us.shape

(67994, 22)